# Generated by Django 3.0.3 on 2020-02-12 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ghostpost', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ghostpost',
            name='date',
        ),
    ]
