# Generated by Django 3.0.3 on 2020-02-13 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghostpost', '0003_auto_20200213_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ghostpost',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ghostpost',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
